### ISSUE TITLE
Some type declarations are wrong.

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain-sdk-js#245]
* [ ] The parameter of `AssetMintOutput.fromJSON` is not declared as JSON object.
https://github.com/CodeChain-io/codechain-sdk-js/blob/023fb7eaaf8eaf7ef996ab1edf6e1820d2771847/src/core/transaction/AssetMintOutput.ts#L13-L16
* [ ] The parameter of `AssetTransferOutput.fromJSON` is not declared as JSON object.
https://github.com/CodeChain-io/codechain-sdk-js/blob/023fb7eaaf8eaf7ef996ab1edf6e1820d2771847/src/core/transaction/AssetTransferOutput.ts#L33
* [ ] `output` field of the parameter of `AssetMintTransaction` should not be a `AssetMintOutput`
https://github.com/CodeChain-io/codechain-sdk-js/blob/023fb7eaaf8eaf7ef996ab1edf6e1820d2771847/src/core/transaction/AssetMintTransaction.ts#L67-L82

**Comment by joojis** [comment]
Fixed at: https://github.com/CodeChain-io/codechain-sdk-js/pull/253

Regarding the third item, I changed the constructor implementation instead of changing the type.
(https://github.com/CodeChain-io/codechain-sdk-js/pull/253/commits/e9e7bd5405c461e6450e31c726d081bf76187939#diff-f2ab1e482bebb9418aec037539b0b051L82)
